
FROM busybox

RUN mkdir -p /tmp/activationbase

COPY data/processed/activation_data.csv /tmp/activationbase/activation_data.csv


COPY images/activationBase_AirQualityIndexPredictionModel/Readme.md /tmp/activationbase/Readme.md


WORKDIR /tmp/activationbase



