
FROM busybox

RUN mkdir -p /tmp/activationBase
WORKDIR /activationBase
COPY ../data/processed/activation_data.csv /activationBase/


COPY images/activationBase_AirQualityIndexPredictionModel/Readme.md /activationBase/



