
FROM busybox

RUN mkdir -p /tmp/activationBase

COPY ../data/processed/activation_data.csv /tmp/activationBase/activation_data.csv


COPY images/activationBase_AirQualityIndexPredictionModel/Readme.md /tmp/activationBase/Readme.md



