FROM busybox
RUN mkdir -p /learningbase/train /learningbase/validation

COPY data/processed/training_data.csv /tmp/learningbase/train/training_data.csv

COPY data/processed/test_data.csv /tmp/learningbase/validation/test_data.csv

#COPY Readme.md /Readme.md
COPY images/learningBase_AirQualityIndexPredictionModel/Readme.md /tmp/learningbase/Readme.md




